### ISSUE TITLE
RR complains about missing App Name in Sparkle feed

### ISSUE THREAD

**Issue by workflowsguy** [homebysix/recipe-robot#102]
When I feed the following Sparkle update url to RR

`http://www.iffmpeg.com/iFFmpeg6.appcast`

it complains

```
[ERROR] I wasn't able to determine the name of this app, so I can't make any recipes.
[ERROR]
```

This puzzles me because in the appcast file there is a 

`<name>iFFmpeg</name>`
 
entry. 
Am I missing something here?

**Comment by homebysix** [comment]
Hi @workflowsguy - I've never seen a Sparkle feed formatted like that, and I'm not surprised that Recipe Robot is having trouble parsing it.

However, I do see a download URL listed that looks exactly like a "latest version" zip:
http://www.iffmpeg.com/iFFmpeg.zip

Additionally, on the iFFmpeg home page there's a link to a dmg download:
http://www.iffmpeg.com/iFFmpeg.dmg

Try running either of those URLs through Recipe Robot and see what you get. ;-)
