### ISSUE TITLE
RR creates incorrect CodeSignatureVerifier part for zip archive with pkg file

### ISSUE THREAD

**Issue by workflowsguy** [homebysix/recipe-robot#103]
I let RR create recipes from the Appcast Url

`http://www.macspeech.com/appcast/4.0/de/dictatede_DSA.xml`

This downloads a zip file that conatins a pkg that contains an app file.
RR creates a CodeSignatureVerifier processor step with inputs for the app file instead of the pkg file.

When running the recipe with AutoPkg, it will fail on the CodeSignatureVerifier step with an IMO non-descript error message.

I do not know if this is an error in RR or something that has to be corrected manually in the recipe?

**Comment by homebysix** [comment]
This is definitely a good test case for us when we start trying to solve #27. For now, I'd recommend manually adjusting the CodeSignatureVerifier arguments as needed.
