### ISSUE TITLE
correct repo for filewave importer and input source path

### ISSUE THREAD

**Issue by cv-rao** [homebysix/recipe-robot#104]
for filewave recipes, should the filewave importer processor not be:
			<key>Processor</key>
			<string>com.github.autopkg.filewave.FWTool/FileWaveImporter</string>

also should the path for import source not be:

				<key>fw_import_source</key>
				<string>%RECIPE_CACHE_DIR%/%NAME%/Applications/%NAME%.app</string>

i had to make the above corrections to successfully run the filewave recipes generated by rr.

thank you btw for a great utility!

**Comment by erikng** [comment]
*waves to CV*

Nice to see you on github.

**Comment by homebysix** [comment]
Thanks! Queued up for 1.0.3.
