### ISSUE TITLE
Docker for Mac Beta Error

### ISSUE THREAD

**Issue by BaddMann** [homebysix/recipe-robot#107]
Docker For Mac is a cool app and I can't wait until it becomes real production.
Was hoping to have munki deliver it to my test bench and create a swarm as a post install.
...but that's besides the point.

It's having no luck with recipe-robot, might want to catch this before it becomes production:

Sparkle Feed: https://download.docker.com/mac/beta/appcast.xml

Error Message: 

> > [ERROR] Recipe Robot exploded with unexpected error: RecipeIdentifierPrefix
> Traceback (most recent call last):
>   File "./recipe-robot", line 98, in main
>     time, _ = recipe_robot_lib.generate_recipes(facts, prefs)  # pylint: disable=assignment-from-no-return
>   File "/Applications/Recipe Robot.app/Contents/Resources/scripts/recipe_robot_lib/tools.py", line 112, in run_func
>     result = func(*args, **kwargs)
>   File "/Applications/Recipe Robot.app/Contents/Resources/scripts/recipe_robot_lib/recipe_generator.py", line 103, in generate_recipes
>     build_recipes(facts, preferred, prefs)
>   File "/Applications/Recipe Robot.app/Contents/Resources/scripts/recipe_robot_lib/recipe_generator.py", line 148, in build_recipes
>     keys["Identifier"] = "%s.%s.%s" % (prefs["RecipeIdentifierPrefix"],
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/objc/_convenience.py", line 162, in __getitem__objectForKey_
>     return container_unwrap(res, KeyError, key)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/objc/_convenience.py", line 659, in container_unwrap
>     raise exc_type(*exc_args)
> KeyError: 'RecipeIdentifierPrefix'
> 
> [ERROR]

**Comment by erikng** [comment]
https://github.com/chilcote/autopkg-recipes/tree/master/Docker

Joe should be merging his recipes soon to the autopkg group.

**Comment by homebysix** [comment]
I just ran the same Sparkle feed through Recipe Robot and got the same output that Joe got.

@BaddMann, you may want to ensure that you've set your preferred recipe identifier prefix. Run `recipe-robot --config` and you'll be prompted for this and other required settings.

**Comment by BaddMann** [comment]
Ok then something is causing my issues.
If I used home brew to install other versions of Python could this cause this behavior?

**Comment by homebysix** [comment]
@BaddMann, first try setting your preferred recipe identifier prefix using my instructions above. If that doesn't work, let me know and we'll look deeper.

**Comment by BaddMann** [comment]
Oh no!! 
I must of just installed RR on this computer and not configured it!
I'm so sorry.

**Comment by homebysix** [comment]
@BaddMann It happens to all of us. :-)
