### ISSUE TITLE
Progress bar eats PuTTY terminal

### ISSUE THREAD

**Issue by n8felton** [homebysix/recipe-robot#108]
Here is a fun one for you: http://i.imgur.com/N6VcnQR.gifv

**Comment by homebysix** [comment]
Thanks @n8felton! Would you mind testing out [this](https://github.com/homebysix/recipe-robot/tree/108-hotfix) branch?

If that branch doesn't work, my next best advice would be to run with the `--app-mode` flag, which suppresses progress indication.

**Comment by n8felton** [comment]
Sorry, missed the feedback on this. Still experiencing the same issue, but using --app-mode appears to work much better. Thanks for updates.

**Comment by homebysix** [comment]
You might find version 1.0.4, just released, behaves better.

**Comment by n8felton** [comment]
I just tested with the `master` branch and received the same results.

If you want to test and see for yourself:
`./recipe-robot -v https://flixel.com/products/mac/pro/download/`
http://imgur.com/UZ9G9Nk

`./recipe-robot -v --app-mode https://flixel.com/products/mac/pro/download/`
http://imgur.com/yHwW5js

**Comment by homebysix** [comment]
OK, I guess I don't know what's going on there. If `--app-mode` works well, I'd recommend keep using that.
