### ISSUE TITLE
Allow recipe duplication

### ISSUE THREAD

**Issue by ygini** [homebysix/recipe-robot#109]
Hi

Lot of recipes are unmaintained nowadays and when we try to use Recipe Robot to make a new version we hit the following error:

```
[ERROR] Sorry, AutoPkg recipes already exist for this app, and I can't blend new recipes with existing recipes.

Here are my suggestions:
	- See if one of the above recipes meets your needs, either as-is or using an override.
	- Or write your own recipe using one of the above as the ParentRecipe.
```

This is annoying. Recipe Robot could make me win a lot of time here and in the end make me loose it because of duplication limitation.

The main idea behind this lock is good but we need a way to get over it.

**Comment by erikng** [comment]
And once the new recipe is written are you going to submit a PR, duplicate it in the autopkg recipe list or keep it internal only?

On Aug 10, 2016, at 6:27 AM, Yoann Gini <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi

Lot of recipes are unmaintained nowadays and when we try to use Recipe Robot to make a new version we hit the following error:

[ERROR] Sorry, AutoPkg recipes already exist for this app, and I can't blend new recipes with existing recipes.

Here are my suggestions:
    - See if one of the above recipes meets your needs, either as-is or using an override.
    - Or write your own recipe using one of the above as the ParentRecipe.


This is annoying. Recipe Robot could make me win a lot of time here and in the end make me loose it because of duplication limitation.

The main idea behind this lock is good but we need a way to get over it.

-

**Comment by ygini** [comment]
It depend.

If the existing one is still maintained but I’ve did things differently OR if the original one isn’t maintained and on an abandoned repo any more I will do a duplicate (and I will do it in any ways).

If the original one isn’t updated but still on a active repo I will do a PR.

**Comment by erikng** [comment]
Can you define isn't maintained/abandoned?

I just recently went through this and while one autopkg author was no longer maintaining the recipes actively, they were not abandoned - he gladly accepted PRs.

On Aug 10, 2016, at 8:38 AM, Yoann Gini <notifications@github.com<mailto:notifications@github.com>> wrote:

It depend.

If the existing one is still maintained but I've did things differently OR if the original one isn't maintained and on an abandoned repo any more I will do a duplicate (and I will do it in any ways).

If the original one isn't updated but still on a active repo I will do a PR.

-

**Comment by homebysix** [comment]
Hi @ygini - It's intentionally undocumented, but there is a way to get around the "recipe already exists" obstacle:
- If you're running Recipe Robot at the command line, add the `--ignore-existing` argument.
- If you're running the Recipe Robot app, hold Option to reveal the "Ignore existing recipes" checkbox before you provide a URL or app as input.

I don't want to encourage people to upload recipes that duplicate the behavior of recipes that have already been written and publicly shared, but `--ignore-existing` does come in useful for [auditing existing recipes](https://youtu.be/5VKDzY8bBxI?t=1825) ([PDF](http://macadmins.psu.edu/wp-content/uploads/sites/24696/2016/06/psumac2016-81-Writing-better-AutoPkg-recipes-with-Recipe-Robot.pdf) page 42) or [creating child recipes based on existing parents](https://youtu.be/5VKDzY8bBxI?t=2829) ([PDF](http://macadmins.psu.edu/wp-content/uploads/sites/24696/2016/06/psumac2016-81-Writing-better-AutoPkg-recipes-with-Recipe-Robot.pdf) page 54).

Hope that answers your question!

**Comment by ygini** [comment]
Hi

This is perfect for me
