### ISSUE TITLE
RR cannot find app in package

### ISSUE THREAD

**Issue by danlockcuff** [homebysix/recipe-robot#125]
Hey, I am trying to process this app https://www.meistertask.com/files/MeisterTask_osx.pkg and I am getting this error. Is this a RR issue or the creator of the app?
Thanks

> Processing https://www.meistertask.com/files/MeisterTask_osx.pkg ...
Input path looks like a download URL.
    Download URL is: https://www.meistertask.com/files/MeisterTask_osx.pkg
Downloading file for further inspection...
    9.99%
    19.97%
    29.96%
    39.95%
    49.93%
    59.92%
    69.91%
    79.89%
    89.88%
    99.87%
    Downloaded to /Users/user456/Library/Caches/Recipe Robot/2017-06-15_14-39-43_614520/MeisterTask_osx.pkg
Determining download format...
    File extension is pkg
Opening downloaded file...
    Download format is pkg
Checking whether package is signed...
    Package is signed
Getting developer from pkg signature...
    Developer is: MeisterLabs
Getting package signature authority names...
    3 authority names recorded
Expanding package to look for clues...
    Package expanded to: /Users/user456/Library/Caches/Recipe Robot/2017-06-15_14-39-43_614520/expanded
Getting information from PackageInfo file...
    Bundle identifier: com.meisterlabs.meistertask.desktop
    Install location: /Applications
    Install filename: Applications
Extracting the package payload to see if we can find an app...
    Did not find an app in the package payload
[ERROR] I wasn't able to gather enough information about this app to make recipes. If you saw any warnings above, they may contain more specific information.
[ERROR]

**Comment by macprince** [comment]
I'm experiencing the same thing when trying to create a recipe for Google Drive File Stream. There definitely is an app in the package payload.

>                       -----------------------------------
>                      |  Welcome to Recipe Robot v1.0.5.  |
>                       -----------------------------------
>                                 \   _[]_
>                                  \  [oo]
>                                    d-||-b
>                                      ||
>                                    _/  \_
>     
> Processing /Users/dan/Downloads/GoogleDriveFileStream.dmg ...
> Input path looks like a disk image.
>     Download URL found in file metadata: https://dl.google.com/drive-file-stream/GoogleDriveFileStream.dmg
>     Successfully mounted disk image
> Checking whether package is signed...
>     Package is signed
> Getting developer from pkg signature...
>     Developer is: Google, Inc.
> Getting package signature authority names...
>     3 authority names recorded
> Expanding package to look for clues...
>     Package expanded to: /Users/dan/Library/Caches/Recipe Robot/2017-09-30_20-52-16_665243/expanded
> Getting information from PackageInfo file...
>     Bundle identifier: com.google.pkg.Keystone
>     Install location: /
>     Install filename: 
> Extracting the package payload to see if we can find an app...
>     Did not find an app in the package payload
> Getting information from PackageInfo file...
>     Install location: /Applications
>     Install filename: Applications
> Extracting the package payload to see if we can find an app...
>     Did not find an app in the package payload
> [ERROR] I wasn't able to gather enough information about this app to make recipes. If you saw any warnings above, they may contain more specific information.
> [ERROR] 
>                                     _[]_
>                                     [xx]
>                                    q-||-p
>                                      ||
>                                    _/  \_
>     
> [0m

**Comment by homebysix** [comment]
@danlockcuff @macprince - You've discovered what I already suspected: that Recipe Robot's support for pkg files is experimental at best. This is something I've been meaning to dive deeper into. See #27.

I'm going to add your two examples into #27 for future research purposes. Thank you!
