### ISSUE TITLE
Using Expected Authority Names is obsolete

### ISSUE THREAD

**Issue by jelockwood** [homebysix/recipe-robot#128]
The (GitHub) recipe that Robot Recipe 1.0.5 generated included Code Signature Verification entries referring to 'Expected_Authority_Names' which AutoPkg considers to be obsolete and so causes the recipe to fail.

This was easy enough to resolve by merely deleting these entries from the recipe generated by Recipe Robot.

**Comment by homebysix** [comment]
`expected_authority_names` is no longer used with codesign, but looks like it's still used with pkgutil. Could you give me an example of a recipe that failed as a result of Recipe Robot including the `expected_authority_names` key? That'll help me narrow down the pieces to remove.

**Comment by homebysix** [comment]
Looks like Recipe Robot was selecting the pkg release for Rocket.Chat, and so `expected_authority_names` is expected.

I've made some changes that now cause Recipe Robot to prefer the dmg or zip release, and the resulting CodeSignatureVerifier contains `requirement` as expected.
