### ISSUE TITLE
AutoPkg and GitHub SSL/TLS error in Receipe Robot

### ISSUE THREAD

**Issue by nilsbyte** [homebysix/recipe-robot#132]
See this issue opened by me: https://github.com/autopkg/autopkg/issues/417 (refers https://github.com/autopkg/autopkg/issues/408). 

I think it has to do with the Python scripts that Receipe Bot uses for creating receipes. They are stored inside the application bundle under Contents > Resources > scripts > receipe_robot. All of them call the Python version at `/usr/bin/python` which is 2.7.10 under OSX 10.11 El Capitan which results in the SSL/TLS error when accessing a GitHub URL.

The first line of the Python scripts in side Receipe Bot has to be changed from

```
#!/usr/bin/python
```

to

```
#!/usr/bin/env python
```

This way the scripts use the last defined path for Python (v3.x) when installed which should solve the problem with SSL/TLS.

But it does not. The same error still occurs with the new Shebang line

**Comment by jpenney** [comment]
```
#!/usr/bin/env python
```

This finds the **first** python executable in the search path, not the last.

You can run this in a terminal to show all the python executable found in the search path, in order:

```
$ type -a python
```

**Comment by homebysix** [comment]
Recipe Robot 2+ uses the version of Python 3 shipped with AutoPkg 2+ (and as such requires AutoPkg to be installed).
