### ISSUE TITLE
Recipe Robot explodes if no desired prefix entered

### ISSUE THREAD

**Issue by grahampugh** [homebysix/recipe-robot#135]
Took me a few minutes to figure out what the error was - I hadn't added a desired prefix in the preferences, and this caused a traceback error rather than n explanatory GUI interaction. It would be good to check for this in the script.

**Comment by homebysix** [comment]
Could you try again with the latest master branch? I think I might have fixed that issue for v1.1.0.

**Comment by homebysix** [comment]
RC3 is now available, and should also include this fix: https://github.com/homebysix/recipe-robot/releases/tag/v2.0.0-rc3

**Comment by homebysix** [comment]
This fix should be included in the [2.0.0 release](https://github.com/homebysix/recipe-robot/releases/tag/v2.0.0).
