### ISSUE TITLE
How to handle spaces

### ISSUE THREAD

**Issue by homebysix** [homebysix/recipe-robot#14]
How should we handle apps with spaces in their names? Current behavior is as follows:

a. Recipe identifier does not contain spaces.
b. Recipe filenames don't contain spaces, except for JSS recipes, which do.
c. Recipe `%NAME%` input variable does contain spaces.
d. Packages, downloads, etc based on `%NAME%` do contain spaces.

(a) and (c) are logical and well accepted. I'm not as sure about (b) and (d).

**Comment by sheagcraig** [comment]
If it were a vote, I'd probably go
a. No spaces
b-d. spaces allowed.

But this is based on my experience-not on anything I know for sure in the AutoPkg docs or from looking at a broad range of recipes.

**Comment by sheagcraig** [comment]
Also, Greg says that the ID can _have_ spaces, but I think that looks heinous. That's why JSS recipes style-guide says no, despite everything else using spaces.
