### ISSUE TITLE
Developer value breaks MunkiAdmin when set as array

### ISSUE THREAD

**Issue by HaniAlshikh** [homebysix/recipe-robot#141]
I discovered recipe robot today and its amazing, thanks a lot.

But while playing with it i noticed, that my MunkiAdmin interface breaks every time i add a recipe made with the recipe robot script.
![broken](https://user-images.githubusercontent.com/39484930/52720762-8c844280-2fa8-11e9-8956-6b82fafe6753.png)
![working](https://user-images.githubusercontent.com/39484930/52720764-8c844280-2fa8-11e9-839f-a679aecf2d38.png)

 Adding it however from other source works fine, so i did some diffing and found that the only difference was the Developer key value, which in my case was an array and in the working recipe case was a string
![diff](https://user-images.githubusercontent.com/39484930/52720763-8c844280-2fa8-11e9-87cf-63ae12c70024.png)

i made the recipe using this command
recipe-robot --ignore-existing https://github.com/homebysix/recipe-robot

and used this" recipe for compression
https://github.com/autopkg/homebysix-recipes/blob/master/Recipe%20Robot/Recipe%20Robot.munki.recipe

**Comment by homebysix** [comment]
Hi @HaniAlshikh - Thanks for reporting this issue! The `developer` value should indeed be a string. However I can't reproduce the issue on my Mac on v1.1.0, even using the exact command you used.

I'm going to try a few more test recipes to see whether I can make it happen.

**Comment by homebysix** [comment]
Found it! Turns out the issue only occurs when the new `StripDeveloperSuffixes` preference is absent or False. The fix is queued up for version 1.1.1, which I'll try to get out soon. Thanks!

**Comment by HaniAlshikh** [comment]
Great, and thank you for the hard work
