### ISSUE TITLE
Under macOS Catalina, Recipe formats check boxes are missing in Preferences

### ISSUE THREAD

**Issue by WardsParadox** [homebysix/recipe-robot#149]
**Describe the bug**
When launched in Catalina, the RecipeRobot preferences pane to choose which recipes to generate do not show (see screenshot below.

**To Reproduce**
1. Open RecipeRobot
2. Go to Preferences (CMD + ,)
3. See issue.

**Expected behavior**
User should be able to select the recipe formats.

**Screenshots**
![2019-08-16 at 2 53 PM](https://user-images.githubusercontent.com/8117192/63197974-927ddd80-c036-11e9-8486-01bb7298f204.png)

**Desktop (please complete the following information):**
 - macOS: 10.15 19A526h
 - Recipe Robot Version: 11.2
 - `which python`: /usr/bin/python
 - `python --version`: 2.7.16

**Comment by homebysix** [comment]
Hi @WardsParadox - Could you try downloading the [Recipe Robot 2.0.0 release candidate](https://github.com/homebysix/recipe-robot/releases/tag/v2.0.0-rc1), and let me know if that solves your issue? Thank you.

**Comment by homebysix** [comment]
@WardsParadox - RC3 is now available — give that a try? https://github.com/homebysix/recipe-robot/releases/tag/v2.0.0-rc3

**Comment by WardsParadox** [comment]
@homebysix Sorry! Been slammed at work. I'll throw the latest RC on our server and check.

**Comment by WardsParadox** [comment]
Confirmed on Catalina + Bug Sire this is fixed in RC
