### ISSUE TITLE
In 1.1.2 last sparkle item picked instead of latest

### ISSUE THREAD

**Issue by andrewzirkel** [homebysix/recipe-robot#150]
**Describe the bug**
In 1.1.2 when processing a sparkle feed with multiple items the last item in the feed is picked instead of the latest version.  This results in an error if the last item is not available.  In 1.1.1 the latest versioned item is picked.

**To Reproduce**
Consider this feed: https://www.kutasoftware.com/updates/appcast_a1m.xml
1.1.2 downloads the last item in the feed instead of the latest version
This failed since the last item is no longer available

**Expected behavior**
The latest version should be downloaded if there is version information.

**Desktop (please complete the following information):**
 - macOS: 10.14.5
 - Recipe Robot Version: 1.1.2
 - `which python`: /usr/bin/python
 - `python --version`: Python 2.7.10

**Comment by homebysix** [comment]
The Sparkle feed in this example is no longer active, however the core problem should have been addressed by this: https://github.com/homebysix/recipe-robot/commit/2767a34f9c930df1016030588e4bf1add9373cb0
