### ISSUE TITLE
Can you add a jss-upload to this app?

### ISSUE THREAD

**Issue by kylejericson** [homebysix/recipe-robot#153]
**Is your feature request related to a problem? Please describe.**
Feature request. This is nice to just upload the PKG to Jamf.
**Describe the solution you'd like**
Here is an example recipe
https://github.com/kylejericson/autopkg-recipes/tree/master/BBEdit
**Describe alternatives you've considered**
Thats it
**Additional context**

**Comment by homebysix** [comment]
Hi @kylejericson - Is there a `NAME` input variable missing from that recipe, or does the recipe just depend on inheriting the name from its parent?

**Comment by kylejericson** [comment]
I believe it's from the parent. I have a few other ones in that repo you could compare.

**Comment by homebysix** [comment]
Update on this: feature planned for v2.0.0, which you can test on [this branch](https://github.com/homebysix/recipe-robot/tree/2.0.0-dev) using the command line script.

**Comment by homebysix** [comment]
This feature is included in the [2.0.0 release](https://github.com/homebysix/recipe-robot/releases/tag/v2.0.0). Thanks for the suggestion!
