### ISSUE TITLE
1.2.0 DMG is corrupted

### ISSUE THREAD

**Issue by niallrmurphy** [homebysix/recipe-robot#154]
**Describe the bug**
When I download the 1.2.0 DMG and attempt to execute the app, the Finder puts up a message after the "Verifying..." dialog box disappears which says:
'“Recipe Robot” is damaged and can’t be opened. You should eject the disk image.'

**To Reproduce**
1. Click on the DMG for 1.2.0 on the github site.
2. Download
3. Double-click to mount
4. Double-click on app

**Expected behavior**
Application should launch

**Screenshots**

**Desktop (please complete the following information):**
 - macOS: [e.g. 10.14.6]
 - Recipe Robot Version: [e.g. 1.2.0
 - `which python`: [N/A]
 - `python --version`: [N/A]

**Additional context**
This version was only half an hour old, so it's plausible something was messed up in signing, build, upload, etc.

**Comment by homebysix** [comment]
Thanks for reporting! I think I need to find a new app for building that DMG.

I updated the release — try again now?

**Comment by kevinmcox** [comment]
I'm seeing the same thing just now.

**Comment by Lotusshaney** [comment]
Opens fine for me here in the UK

**Comment by niallrmurphy** [comment]
I still see the old broken version, from IE

**Comment by homebysix** [comment]
Hi @niallrmurphy - I think I figured out the issue. Xcode 11 wanted to add ad-hoc signing automatically.

Could you try this build and let me know how it looks? https://www.dropbox.com/s/y2w3w1bmzqwue85/RecipeRobot-1.2.1.dmg?dl=1

**Comment by niallrmurphy** [comment]
Works fine, thanks!
