### ISSUE TITLE
Recipe Robot not signed

### ISSUE THREAD

**Issue by jby** [homebysix/recipe-robot#157]
**Describe the bug**
**Screenshots**
![image](https://user-images.githubusercontent.com/1584888/78550317-2a1d7f80-7804-11ea-863c-22f6e7b1e179.png)

**Desktop (please complete the following information):**
 - macOS: 10.15.4
 - Recipe Robot Version: 1.2.1
 - `which python`: /usr/local/bin/python
 - `python --version`: Python 2.7.17

Any plans on signing it?

**Comment by homebysix** [comment]
No plans to sign Recipe Robot at this time.
