### ISSUE TITLE
Help wanted: Problem transitioning to Python3

### ISSUE THREAD

**Issue by homebysix** [homebysix/recipe-robot#160]
Recipe Robot's transition to Python 3 has been delayed due to a problem with the way the `Notifying*` object types interact with the Swift UI app wrapper. The code at issue is on the [2.0.0-dev](https://github.com/homebysix/recipe-robot/tree/2.0.0-dev) branch, and I would welcome another pair of eyes on it.

Requirements:
- Xcode (I'm building with Xcode 11.3.1 on Mojave)
- Already configured Recipe Robot once before (recipe identifier prefix, recipe types, etc)
- AutoPkg 2.x installed

1. Clone the repo locally and switch to the 2.0.0-dev branch.
2. Run this command and note that it succeeds building recipes:

        ./scripts/recipe-robot --verbose --ignore-existing --app-mode https://coconut-flavour.com/updates/coconutBattery.xml

3. Open ./app/Recipe Robot.xcodeproj in Xcode
4. Build and run the app.
5. Hold option to reveal the "Ignore existing" checkbox, and check it.

    ![Screen Shot 2020-05-02 at 11 10 01 AM](https://user-images.githubusercontent.com/7801391/80872233-85a52680-8c65-11ea-88cd-8ecc408a6461.png)

6. Enter the same input URL as you provided to the command line tool: `https://coconut-flavour.com/updates/coconutBattery.xml`

7. Click the **Do It** button and observe:

    ![Screen Shot 2020-05-02 at 11 00 15 AM](https://user-images.githubusercontent.com/7801391/80872252-ab323000-8c65-11ea-9cc2-0a42e50b60b9.png)

    - No progress messages are displayed
    - The run exits nonzero (as indicated by "Oops" message)

Expected behavior would be for the app output and the script output to match, given the same input.

I've traced the source of this error to the best of my (non `pdb`-savvy) ability, and it looks to be an issue with how the `NotifyingList`, `NotifyingString`, and other objects use `NSDistributedNotificationCenter` (e.g. https://github.com/homebysix/recipe-robot/blob/2.0.0-dev/scripts/recipe_robot_lib/facts.py#L116). This would explain why it's an issue in the app and not at the command line; these notifications are how the app receives status information from the command line tool. If the notifications aren't working, no output would be displayed.

My theory: the version of PyObjC [included](https://github.com/autopkg/autopkg/blob/master/requirements.txt) in AutoPkg 2.x's Python 3 framework requires changes for these notifying objects in order to make them communicate to the Recipe Robot app in Python 3.

Thanks in advance if you're able to reproduce this issue and provide any suggestions.

**Comment by StuFyfe** [comment]
I've reproduced issue, got exactly the same results as you.
I did notice an extra "--" gets passed in arguments from the GUI, but that doesn't seem to be related to the problem.
I've run out of useful skills though so can't offer anything constructive about why.

**Comment by homebysix** [comment]
Fixed by #163 — thanks @sheagcraig!
