### ISSUE TITLE
Recipe Robot 2.0.0 dev not finding AutoPkg

### ISSUE THREAD

**Issue by Honestpuck** [homebysix/recipe-robot#162]
**Describe the bug**
Running the script and it reports `[ERROR] AutoPkg must be installed!`

**To Reproduce**
1. Clone and switch to branch 2.0.0. dev
2. Run `./scripts/recipe-robot --verbose https://www.vysor.io/download/osx`
3. Get error `[ERROR] AutoPkg must be installed!` and recipe robot returns 1
4. run `autopkg version`
5. Get `2.0.1`

**Expected behavior**
Recipe created
**Desktop (please complete the following information):**
 - macOS: 10.14.6
 - Recipe Robot Version: 2.0.0 dev
 - `which python`: /anaconda3/bin/python
 - `python --version`: Python 3.7.3

**Additional context**
Shell is zsh

**Comment by homebysix** [comment]
Hi @Honestpuck - Could you also send me the output of `which autopkg`?

**Comment by Honestpuck** [comment]
@homebysix Sorry, missed your message. `which autopkg`: /usr/local/bin/autopkg

**Comment by homebysix** [comment]
Could you try downloading the [Recipe Robot 2.0.0 release candidate](https://github.com/homebysix/recipe-robot/releases/tag/v2.0.0-rc1), and let me know if the issue persists? Thank you!

**Comment by Honestpuck** [comment]
I can't replicate it any more with either the old 2.0.0 dev or the release candidate. I think it should be closed a a strange anaconda problem.
