### ISSUE TITLE
traceback encountered with App and Python script when any command is entered

### ISSUE THREAD

**Issue by VirtualDisk** [homebysix/recipe-robot#167]
**Describe the bug**
Howdy! I'm trying out this app for the first time and having a lot of issues unfortunately. I encountered a traceback after doing the initial setup with the GUI and it doesn't seem to want to do anything else. 

**To Reproduce**
1. Complete the symlink for recipe robot.
2. run $ recipe-robot
3. traceback follows.

`❯ recipe-robot
Traceback (most recent call last):
  File "/usr/local/bin/recipe-robot", line 42, in <module>
    import recipe_robot_lib
  File "/Applications/Recipe Robot.app/Contents/Resources/scripts/recipe_robot_lib/__init__.py", line 26, in <module>
    from .recipe_generator import generate_recipes
  File "/Applications/Recipe Robot.app/Contents/Resources/scripts/recipe_robot_lib/recipe_generator.py", line 34, in <module>
    from . import processor
  File "/Applications/Recipe Robot.app/Contents/Resources/scripts/recipe_robot_lib/processor.py", line 38, in <module>
    import autopkglib
  File "/Library/AutoPkg/autopkglib/__init__.py", line 168
    raise PreferenceError(f"Could not synchronize preference {key}")
                                                                  ^
SyntaxError: invalid syntax`

![Screen Shot 2020-10-02 at 10 15 19 AM](https://user-images.githubusercontent.com/15205414/94933508-776b6880-0498-11eb-9107-961e84ea58ed.png)

**Expected behavior**
Recipe Robot should generate a recipe, or at least run through the CLI config flow.

**Desktop (please complete the following information):**
 - macOS: 10.15.7
 - Recipe Robot Version: 2.0.0 (tried dev and non-dev branch)
 - `which python`: /usr/bin/python
 - `python --version`: Python 2.7.16

**Comment by homebysix** [comment]
Hi @VirtualDisk - Could you try downloading the [Recipe Robot 2.0.0 release candidate](https://github.com/homebysix/recipe-robot/releases/tag/v2.0.0-rc1), and let me know if that solves your issue? Thank you.

**Comment by peterkelm** [comment]
@homebysix, I came across the same issue and tried the 2.0 RC you linked above. No change, same behavior...

**Comment by peterkelm** [comment]
Same as #156.

**Comment by homebysix** [comment]
Hi @peterkelm - Could you post the full command you ran to call `recipe-robot` and the resulting output?

Also could you post the output of `autopkg version`?

I'll try to reproduce the issue on a fresh 10.15.7 Mac.

**Comment by peterkelm** [comment]
@homebysix, see below:

# autopkg version
2.2

# recipe-robot -c     
Traceback (most recent call last):
  File "recipe-robot", line 42, in <module>
    import recipe_robot_lib
  File "/###redacted###/autopkg-recipes/recipe-robot-2.0.0-rc1/scripts/recipe_robot_lib/__init__.py", line 26, in <module>
    from .recipe_generator import generate_recipes
  File "/###redacted###/autopkg-recipes/recipe-robot-2.0.0-rc1/scripts/recipe_robot_lib/recipe_generator.py", line 34, in <module>
    from . import processor
  File "/###redacted###/autopkg-recipes/recipe-robot-2.0.0-rc1/scripts/recipe_robot_lib/processor.py", line 38, in <module>
    import autopkglib
  File "/Library/AutoPkg/autopkglib/__init__.py", line 168
    raise PreferenceError(f"Could not synchronize preference {key}")
                                                                  ^
SyntaxError: invalid syntax

**Comment by homebysix** [comment]
@peterkelm - I couldn't reproduce your exact issue, but could you try again with RC2, available [here](https://github.com/homebysix/recipe-robot/releases/tag/v2.0.0-rc2)? Thank you.

**Comment by homebysix** [comment]
@peterkelm - RC3 is now available, please give that a try: https://github.com/homebysix/recipe-robot/releases/tag/v2.0.0-rc3

**Comment by peterkelm** [comment]
@homebysix, just tried RC3 and it works as expected - not only the config/setup but also doing a new recipes. Thanks a million!!!

**Comment by homebysix** [comment]
Thanks! Fix included in [2.0.0 release](https://github.com/homebysix/recipe-robot/releases/tag/v2.0.0).
