### ISSUE TITLE
Recipe Robot v2b1 GUI output doesn't appear until it completes

### ISSUE THREAD

**Issue by apizz** [homebysix/recipe-robot#169]
**Describe the bug**
When an app is dragged on a Mac running 10.15.6 into the Recipe Robot window or a URL is pasted, no text output in the main app window appears until the run is completed.

**To Reproduce**
1. Open Recipe Robot
2. Drag installed app into window or paste URL
3. Observe no text output appears until run is completed

**Expected behavior**
Text output appears immediately and while Recipe Robot analyzes & processes the app / URL

**Screenshots**
<img width="600" alt="Screen Shot 2020-10-09 at 12 51 50 PM" src="https://user-images.githubusercontent.com/11789931/95610889-0b0bde80-0a2f-11eb-8c26-a14589be9e17.png">

**Desktop (please complete the following information):**
 - macOS: 10.15.6
 - Recipe Robot Version: 2.0.0 b1
 - `which python`: /usr/bin/python
 - `python --version`: 2.7.16

**Additional context**
I did this for an app which already has a recipe just to test

**Comment by apizz** [comment]
🤦 .... from release notes `Script output does not appear in the app until the script is completely done processing. I hope to restore realtime output in a later version.`

**Comment by homebysix** [comment]
Keep an eye on #170.
