### ISSUE TITLE
Make preferences menu interactive while retaining scrollback

### ISSUE THREAD

**Issue by homebysix** [homebysix/recipe-robot#17]
Right now an interactive prompt appears when the Recipe Robot script is first run. The user is prompted for their preferred identifier, recipe save location, and preferred recipe types.

During this prompt, it would be excellent to "refresh" the screen while retaining scrollback. Right now the act of toggling recipe types on/off causes the entire list of recipes to appear again.

I believe the right way to do this is using the `curses` module, although I'm not familiar with it yet.

This will not affect the Mac app, which will have a separate interface for prompting for preferences.

**Comment by sheagcraig** [comment]
curses _can_ do it.

However, should it?

I think it may appear heinous to the eyes of gui users... But they're going to be using the GUI. As a die-hard CLI user, I wouldn't expect my menus to redraw the screen on me.

**Comment by homebysix** [comment]
True, the people who care a lot about pretty menus will use the Mac app.

So you think the script prefs interface is good to go for 1.0?
