### ISSUE TITLE
Recipe Robot 2.0: Incorrect "Minimum System version" Requirement?

### ISSUE THREAD

**Issue by workflowsguy** [homebysix/recipe-robot#180]
The Requirements Section of the project states "macOS 10.13 and above", yet RR 2.0.app's info plist shows `Minimum system version` as 10.15

**Comment by homebysix** [comment]
Good catch — 10.13 is correct for now. I may need to increase to 10.15 soon in order to add some features I have planned.

I'll update the Info.plist in upcoming v2.1 back to 10.13.
