### ISSUE TITLE
Support for JamfUploader recipes

### ISSUE THREAD

**Issue by homebysix** [homebysix/recipe-robot#187]
JamfUploader recipes are an alternative to JSSImporter recipes, and are explained in more detail here: https://github.com/grahampugh/jamf-upload/wiki/JamfUploader-AutoPkg-Processors

This seems like something Recipe Robot could help automate.

**Comment by Lotusshaney** [comment]
Please do this, Robot is amazing and having jamfUploader support would be fantastic

**Comment by homebysix** [comment]
This is supported now as of v2.3.1.
