### ISSUE TITLE
Avoid SSLv3 handshake error while using urlopen()

### ISSUE THREAD

**Issue by homebysix** [homebysix/recipe-robot#19]
Might not be possible, but I want to see if we can find a way around SSLv3 handshake errors when trying to access various URLs. Here's an example:

```
$ recipe-robot -v http://www.macroplant.com/latest-binaries/adapter-mac.dmg

                      -----------------------------------
                     |  Welcome to Recipe Robot v0.0.4.  |
                      -----------------------------------
                                \   _[]_
                                 \  [oo]
                                   d-||-b
                                     ||
                                   _/  \_

Processing http://www.macroplant.com/latest-binaries/adapter-mac.dmg ...
Input path looks like a download URL.
    Download URL is: http://www.macroplant.com/latest-binaries/adapter-mac.dmg
Downloading file for further inspection...
[WARNING] I got an SSLv3 handshake error, and I don't yet know what to do with that. (<urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)>)
[ERROR] I wasn't able to determine the name of this app, so I can't make any recipes.
```

**Comment by sheagcraig** [comment]
I think the options are:
1.) Use PyObjC/NSURLConnection (look at Gurl.py in Munki). Benefits: Can do modern TLS stuff. Downsides: Forces us to use System Python. Lots of PyObjC!
2.) Shell out to curl. Allegedly curl can handle this stuff. Benefits: We know it works. Downsides: Cheesy.
3.) Add requests as a dependency (can be bundled with recipe robot due to license). Benefits: I have experience with this method. Downsides: See "Benefits".
4.) Quit dicking around and use python3.

**Comment by homebysix** [comment]
@eahrold Do you have an opinion? All the options seem equally good/bad.

**Comment by eahrold** [comment]
Not on this one. But I like the acronym QDAUP3

**Comment by jgstew** [comment]
I'm fairly certain there is a way to suppress this using pure python using the built in libraries. I think @hansen-m has done this for other autopkg related python scripts.

**Comment by hansen-m** [comment]
Yeah, this issue is becoming more common. I don't know the exact details here, but can you workaround it with this monkey-patch...

https://github.com/autopkg/recipes/pull/100

**Comment by homebysix** [comment]
Is anybody still having this issue recently? The example given now works fine for me:
```
recipe-robot -v http://www.macroplant.com/latest-binaries/adapter-mac.dmg
```
The fix is probably the result of a change on macroplant.com, but could also be related to the fact that I'm testing on a newer version of macOS than I was back in 2015.

If the issue is rare or gone, I'll close this issue.

**Comment by homebysix** [comment]
If this issue wasn't already resolved in 2019, it should have been resolved when Recipe Robot switched from urllib to curl in [2.0.0](https://github.com/homebysix/recipe-robot/releases/tag/v2.0.0).
