### ISSUE TITLE
PKG rather than DMG as an option for Munki recipe's

### ISSUE THREAD

**Issue by Lotusshaney** [homebysix/recipe-robot#190]
Is there a way or option to allow for PKG's to be used in Munki recipe's rather than DMG's ?

The Reason is that we are looking to block DMG's being mounted for some users, but would still like to use Munki to deploy updates so PKG's would be dishabille ?

I can modify the recipes after creation to do PKG's but it would be nice to have the option to select type.

**Comment by homebysix** [comment]
This isn't something I need, and I suspect very few people block dmg mounting, so I'm not planning on building it in.

However, if you submit a PR that does this, I'd be open to it. It would need to be a configurable option, with dmg remaining the default.
