### ISSUE TITLE
[ERROR] Sorry, I can't determine which version key to use for this app.

### ISSUE THREAD

**Issue by tetesh** [homebysix/recipe-robot#192]
**Describe the bug**
get [ERROR] Sorry, I can't determine which version key to use for this app.

**To Reproduce**
start work recipe-robot for creating download.recipe 
link dmg: https://dl.influxdata.com/telegraf/releases/telegraf-1.21.3_darwin_amd64.dmg

**Expected behavior**
get the required recipe

**Desktop (please complete the following information):**
 - macOS: 10.14.6
 - Recipe Robot Version: 2.2.0
 - `autopkg version`: 2.3.1
 - `/usr/local/autopkg/python --version`: Python 3.7.5

**Additional context**
I ask you to help create a recipe for telegraf, an error occurs, can I prescribe the version myself if the robot does not succeed?
work log: 
```
 Processing: /Users/munki/Downloads/telegraf-1.21.3_darwin_amd64.dmg
Input path looks like a disk image.
    Download URL found in file metadata: https://dl.influxdata.com/telegraf/releases/telegraf-1.21.3_darwin_amd64.dmg
    Successfully mounted disk image
    Copying Telegraf.app into cache...
Validating app...
    This app seems valid
Getting bundle name...
    Bundle name is: telegraf_entry_mac
Bundle name differs from the actual app filename.
    Actual app filename: Telegraf.app
Getting bundle identifier...
    Bundle identifier is: com.influxdata.telegraf
Checking for a Sparkle feed...
    No Sparkle feed
Determining whether app was downloaded from the Mac App Store...
    App did not come from the App Store
Looking for version key...
[ERROR] Sorry, I can't determine which version key to use for this app.
```

**Comment by homebysix** [comment]
That's because the Telegraf app does not contain any usable version information:

![image](https://user-images.githubusercontent.com/7801391/152012407-000a27f7-8394-4fdd-94cb-2c486a823e3a.png)

You can still write AutoPkg recipes for this app manually, but AutoPkg may have similar problems due to the lack of versioning.

I would recommend reaching out to the developer and suggesting they add a `CFBundleShortVersionString` and/or `CFBundleVersion` key/value to their Info.plist.

**Comment by tetesh** [comment]
Many thanks! I'll figure it out and make the recipe by hand. Probably, such problems as I do not happen often, but it might be worth adding the ability to add the missing keys immediately to the robot recipe if they are not specified in the application. If you do not have time, I will try to figure it out and add this feature

**Comment by tetesh** [comment]
I solved it like this, but it certainly doesn't work in the gui:

```
        if version_key not in ("", None):
            robo_print(
                "Version key is: {} ({})".format(version_key, info_plist[version_key$
                LogLevel.VERBOSE,
                4,
            )
            facts["version_key"] = version_key
        else:
-            raise RoboError(
-                "Sorry, I can't determine which version key to use for this {}.".fo$
-                    bundle_type
-                )
-            )
+            print("Sorry, I can't determine which version key, please enter CFBundle$
+            while True:
+                try:
+                    version_manual = input("Enter version string (x.x or x.x.x): ")
+                    pattern1 = '^\d+\.\d+\.\d+(\r)?$'
+                    pattern2 = '^\d+\.\d+(\r)?$'
+                    match1 = re.fullmatch(pattern1, version_manual)
+                    match2 = re.fullmatch(pattern2, version_manual)
+                    if match1 or match2:
+                        facts["version_key"] = version_manual
+                        break
+                    else:
+                        print("Invalid version")
+                except:
+                    print("Invalid version")

    # Determine path to the app's icon.
    if "icon_path" not in facts and not args.skip_icon:
        icon_path = ""
        robo_print("Looking for icon...", LogLevel.VERBOSE)
        if "CFBundleIconFile" in info_plist:
            icon_path = os.path.join(
                input_path, "Contents", "Resources", info_plist["CFBundleIconFile"]
```

**Comment by homebysix** [comment]
Version formats are varied and [complicated](https://github.com/autopkg/autopkg/blob/3e0441427ddd4281075ac9746f4deaf116509698/Code/autopkglib/__init__.py#L896) to validate. And because missing versions are very rare and often temporary (due to a new developer misunderstanding app conventions, for example) I don't think this is an accommodation I'd build into Recipe Robot.

**Comment by tetesh** [comment]
I found a better option, the [PlistEditor](https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/PlistEditor.py) function, it would be cool to pass arguments through the robot to this function if they are not present initially
Example: https://github.com/autopkg/recipes/blob/master/AdobeAIR/AdobeAIR.pkg.recipe

**Comment by tetesh** [comment]
As for the versions - I agree, it turned out badly. But can exclude checking the value with regular expressions
