### ISSUE TITLE
RecipeRobot --ignore-existing 

### ISSUE THREAD

**Issue by Korbiwev** [homebysix/recipe-robot#204]
Hello everyone, 

I would like to have RecipeRobot write a download and pkg recipe for Handbrake for practice purposes. 

When I put the program into the robot, it tells me that it does not create recipes for this, because there are already some existing. 

I found out that I can work around this problem with the command "--ignore-existing". 

My question now is where I have to enter this command that it work. 

Can anyone help me? 

Thank you very much 

Korbinian

![Screenshot 2024-03-26 at 15 14 27](https://github.com/homebysix/recipe-robot/assets/143584246/0637fd3a-b1d4-436c-92d6-f8520b0f6832)

**Comment by homebysix** [comment]
Hi @Korbiwev - In the Mac app, you can access the Ignore Existing option by holding the Option key. This is intentionally not in the documentation in order to discourage creation of recipes that already exist elsewhere, but for your practice it's fine to do. Thanks!
