### ISSUE TITLE
How to most accurately determine which SourceForge file is the one we want

### ISSUE THREAD

**Issue by homebysix** [homebysix/recipe-robot#21]
Right now Recipe Robot looks for the `files:extra-info` tag marked as `data` in the RSS feed, which seems to work for a subset of SourceForge-hosted files, but not all of them.

For example, here are the filenames and `extra-info` tags for each file in a [GrandPerspective](http://sourceforge.net/projects/grandperspectiv/rss) release:

| Filename | `extra-info` |
| --- | --- |
| README.txt | English text | 
| __GrandPerspective-1_5_1.dmg__ | __data__ |
| GrandPerspective-1_5_1-src.tgz | POSIX tar archive (GNU) (gzip compressed data) |

The one in bold is the actual binary we want to download.

As a counterexample, the latest release of [VLC](http://sourceforge.net/projects/vlc/rss) has an `extra-info` tag `x86 boot sector (bzip2 compressed data)`.

Trying to find the unifying factor that determines "yes, this is the binary you want to download."

**Comment by sheagcraig** [comment]
My initial response was because VLC just doesn't offer a disk image format download. But it does (at least based on looking at the SF site, not the RSS).

Can you provide more examples, with complete data? Is it possible that we're just looking for a filename with extension `.dmg` and with either `data` or `x86 boot sector (bzip2 compressed data)`?

Is one just a standard disk image, and another a compressed one, probably? So maybe we just need to figure out what the SF synonyms for each kind of disk image are?

**Comment by homebysix** [comment]
Here are some examples:

- http://sourceforge.net/projects/grandperspectiv/rss
- http://sourceforge.net/projects/vlc/rss
- http://sourceforge.net/projects/adium/rss
- http://sourceforge.net/projects/cord/rss

It appears that unlike Sparkle feeds, each release is not limited to a single `<item>`. Instead, there is a separate `<item>` for every file in a release, and the release files aren't grouped together at all. Best we can do, I think, is to find the group of items with the most recent `<pubDate>` and then try to determine which `<item>` with that `<pubDate>` is the one we want.

On the other hand, I'm not keen on spending much dev time making Recipe Robot work well with SourceForge, because SourceForge is clearly on the decline.

**Comment by wildeep** [comment]
Another example: [https://sourceforge.net/projects/apcupsd/](https://sourceforge.net/projects/apcupsd/)

**Comment by homebysix** [comment]
Yeah, I'm not inclined to spend any more time on fiddly SourceForge stuff.

**Comment by homebysix** [comment]
I believe @n8felton may have solved this for us! I've added some code in the latest dev branch that should work its way into master eventually.
