### ISSUE TITLE
Handle custom Sparkle namespaces

### ISSUE THREAD

**Issue by homebysix** [homebysix/recipe-robot#22]
Is there such a thing as a Sparkle feed that doesn't use `http://www.andymatuschak.org/xml-namespaces/sparkle` as its namespace? If so, Recipe Robot will probably choke on it.

Here's an example of how this might be resolved:
https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/SparkleUpdateInfoProvider.py#L115-L119

**Comment by sheagcraig** [comment]
I can see that you're already tacking the URL onto everything properly, so I imagine just changing the namespace like you suggested would be all that it would take. If such a thing even exists. I would have to think that with the thousands of recipes you've generated already, you would have come across at least one if they existed!

**Comment by homebysix** [comment]
You're right, I have yet to encounter a Sparkle URL that doesn't use the namespace above. We can revisit this later if needed.
