### ISSUE TITLE
More intelligent detection of the newest item in a Sparkle feed

### ISSUE THREAD

**Issue by homebysix** [homebysix/recipe-robot#23]
Right now Recipe Robot reads all the `sparkle:shortVersionString` and `sparkle:version` information for every item in the feed, and does a basic string comparison to determine which item is the "latest" version. However, this fails easily: `"999" > "1000"`

A better approach would be to get the most recent `pubDate`.

**Comment by sheagcraig** [comment]
Wouldn't it be better to do a version comparison with distutils.version.StrictVersion/LooseVersion?

StrictVersion will probably only work 20% of the time, but LooseVersion should be pretty bombproof.

I would think that a and'ed comparison of LooseVersion and pubDate would be doing the best we could do.
