### ISSUE TITLE
Agree to software license agreements when mounting dmg files

### ISSUE THREAD

**Issue by homebysix** [homebysix/recipe-robot#25]
Right now Recipe Robot requires you to press "y" to agree to the SLA on certain disk images.

```
[WARNING] Please type Y and press Enter to accept the software license agreement.
Agree Y/N? y
```

In order to link this up with the Mac app, we'll need to make this non-interactive.

**Comment by eahrold** [comment]
If the prompt is consistent i.e always "Agree Y/N?" then we can handle this with NSTask by inspecting the stdout string, and presenting the user with a alert window and piping the user input from that to stdin.

If the prompt changes that's another story.

**Comment by homebysix** [comment]
Here's how AutoPkg does it (in Python): https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/DmgMounter.py#L108-L110

If we make it non-interactive in Python, then we don't have to think about it in the Mac app, right?

**Comment by eahrold** [comment]
Correct.  And if it's legally not an issue then I say let's do that.

**Comment by sheagcraig** [comment]
My comment has already been brought up by the illustrious Mr. @eahrold . Can we legally accept a license agreement for someone else?
