### ISSUE TITLE
Are there keys other than SUFeedURL and SUOriginalFeedURL that would help us download an app, given its Info.plist?

### ISSUE THREAD

**Issue by homebysix** [homebysix/recipe-robot#28]
Are there keys other than `SUFeedURL` and `SUOriginalFeedURL` that would help us download an app, given its Info.plist?

I'm guessing the answer is no.

**Comment by sheagcraig** [comment]
I find it extremely unlikely.

Based on a casual survey of apps on my machine, the only info that I saw was the sparkle stuff.

One app, Grand Perspective, had a URL to its website, but the key was GPWebsiteURL, which is clearly just one they made up. So yeah, we could look for any URL's in the plist, but without context that would be basically useless.

I think you're safe.
