### ISSUE TITLE
Create fact_validator() function to determine which recipes we can build

### ISSUE THREAD

**Issue by homebysix** [homebysix/recipe-robot#30]
Right now the `generate_recipes()` function and various `generate_x_recipe()` functions individually determine whether they can proceed, given the info in the `facts` dict. It might be more efficient to have a single `fact_validator()` function that centrally determines which recipes can be built and which should be skipped.

**Comment by sheagcraig** [comment]
Hmmm. I'm not sure.

If this were OOP, there would be some kind of manager class in charge of telling the recipe classes what to do. But it would have no idea of whether a recipe could or could not proceed. That task would be hidden within the recipe.

That said, we _could_ create a recipe generator class that included some base validation code that each sub-recipe type could inherit from and override to add facts specific to their domain. And that would keep redundancy down.

**Comment by homebysix** [comment]
TBH, I think the current approach is decent:

- A `generate_recipes()` function that determines whether we have the basic information needed to produce any recipes at all (app name, how to download the app).
- Specific functions like `generate_pkg_recipe()` that determine whether we have the information needed to produce a certain type of recipe. For a pkg recipe, that would include the bundle identifier.

So I'm unconvinced that we need a `fact_validator()`.

The only thing that's currently not working is this: #44.
