### ISSUE TITLE
Consider whether to output recipes in subfolders

### ISSUE THREAD

**Issue by homebysix** [homebysix/recipe-robot#31]
Most autopkg repos group recipes into folders by developer name or by product name. Should Recipe Robot do that, or leave it up to the user?

**Comment by eahrold** [comment]
I think stay consistent with autopkg and do the grouping whenever possible.

**Comment by homebysix** [comment]
In that case — spaces or no spaces in the folder names (#14)?

**Comment by eahrold** [comment]
I always vote against spaces in file paths. I'm an underscore guy.

**Comment by sheagcraig** [comment]
I think by product sounds best. By developer seems awkward. It requires users to know who makes what.

Personally, I hate spaces in file paths too. However, we obviously see lots of apps with spaces in the filenames, and there's no technical limitation to allowing spaces; I think allow spaces. But not in identifiers!

**Comment by homebysix** [comment]
I think organizing by developer is the standard practice (except for jss-recipes). It doesn't require that users know the name of the developer. The Robot knows! :bulb: 

It's working now, but the perfectionist in me wants to strip the leading "the" and trailing "Inc." Probably more hassle than it's worth.

<img width="238" alt="screen shot 2015-10-05 at 10 55 33 pm" src="https://cloud.githubusercontent.com/assets/7801391/10301162/5f8262d2-6bb4-11e5-88fe-038d1ce346bf.png">

**Comment by homebysix** [comment]
OK, now outputs in subfolders named by developer (unless the developer isn't known, in which case it uses the product name).

For my own repo, I use developer name if there are recipes for more than one of that developer's products, and product name otherwise. I'll continue following that model myself.
