### ISSUE TITLE
Should we warn/prompt when overwriting a file?

### ISSUE THREAD

**Issue by homebysix** [homebysix/recipe-robot#32]
When a png icon file or a recipe already exists in the output directory, should we warn about that? I'm leaning towards no, since I often run Recipe Robot multiple times in a row while making small tweaks, and overwriting existing files is the desired behavior.

If we don't prompt for overwriting, we may want to choose a different default output path than ~/Library/AutoPkg/RecipeOverrides, in order to prevent overwriting existing overrides.

**Comment by sheagcraig** [comment]
I guess I'm out of the loop enough that I don't know why we would be writing to RecipeOverrides?

As for overwriting icon files, presumably recipe repos are going to be _repos_; thus, any changes are going to have to be committed, so a changed icon will be noticed. It's up to the user whether they want to not-include the new icon.

**Comment by homebysix** [comment]
I write to RecipeOverrides because it's probably a bad habit I learned early on. What would be a better default? ~/Library/AutoPkg/Recipe Robot?

Agreed on the icon.

**Comment by homebysix** [comment]
Default save location changed to "~/Library/AutoPkg/Recipe Robot output" which should prevent us from overwriting anything except recipes RR previously generated (which is intended).
