### ISSUE TITLE
Don't increment cumulative recipe count when "doing-over"

### ISSUE THREAD

**Issue by homebysix** [homebysix/recipe-robot#33]
I often run Recipe Robot multiple times in a row while making small tweaks. The end result is only a handful of recipes, but the cumulative count increases on every run.

Might be more accurate not to increment the count if an existing recipe is overwritten (see #32).

**Comment by sheagcraig** [comment]
So should it be renamed to "Unique Recipe Count"? Otherwise, I don't see this as a problem.

Chances are pretty good that once everything is nailed down for release, users are not going to _need_ to run it more than once per product.
