### ISSUE TITLE
Only provide a filename argument to URLDownloader if existing filename is not suitable

### ISSUE THREAD

**Issue by homebysix** [homebysix/recipe-robot#35]
Many recipes based on download URLs benefit from a `filename` argument when including the `URLDownloader` processor:
- http://macrabbit.com/espresso/get
- https://srv3.airdroid.com/p14/web/getbinaryredirect?type=dmg
- http://download.bjango.com/skalapreview/
- https://central.github.com/mac/latest
- https://hephaestus.infinit.io/macosx/installer/Infinit.dmg?t=1441494215512

Others are just fine as-is:
- http://www.ohanaware.com/appwrapper/appWrapper3.zip
- https://download-cdn.getsync.com/stable/osx/BitTorrent-Sync.dmg
- http://static-download.s3-website-us-east-1.amazonaws.com/sketch.zip
- http://www.sonnysoftware.com/Bookends.dmg

How can Recipe Robot determine which is which and apply the `filename` argument intelligently?

**Comment by sheagcraig** [comment]
I think the thing that is in common with the junk names is that they're all redirects, arguments to PHP, or just directories. I would hazard a guess that `if not os.path.splitext(download_url)[1]:` would group the ones that need a `filename`, whereas anything with an extension is (hopefully!) going to be what it says it is.

Well, filtering for `.php`, and maybe `.html, .html`?

So perhaps:
```
_, extension = os.path.splitext("download_url")
if not extension or extension.upper() in NON_FILE_URL_TYPES:
    # Needs a filename.
```

**Comment by homebysix** [comment]
@sheagcraig I started a similar idea in https://github.com/homebysix/recipe-robot/commit/f4855f467187d04d6273f8adc01e3adf9a0f62ef — do you think it has merit?

**Comment by sheagcraig** [comment]
Another thing to consider is that we never are going to hurt anything by specifying a filename.

And if Recipe Robot consistently produces download filenames in a known format, for those people who _do_ want to poke around in the Cache, it will always be obvious I think the snippet I put in above will work, and yours too.

**Comment by homebysix** [comment]
At this time, I'm OK with adding an unnecessary `filename` argument for URLDownloader.
