### ISSUE TITLE
Running with only --config arg causes error

### ISSUE THREAD

**Issue by eahrold** [homebysix/recipe-robot#43]
Running `../recipe-robot/scripts/recipe-robot --config`

Results in "too few arguments" error
Simply appending any arbitrary path to the end fixes the issue.
Not sure where this is exactly but probably want to set the input_path required flag to false when running `--config`

**Comment by homebysix** [comment]
Good catch! I was thinking people would run `--config` in _addition_ to their input path, but I can definitely see why you'd want to change the config without necessarily producing recipes.
