### ISSUE TITLE
Handle preference panes and internet plugins.

### ISSUE THREAD

**Issue by homebysix** [homebysix/recipe-robot#47]
If it's a standard "drag this to your PreferencePanes" or "drag this to your Internet Plugins" dmg, we should be able to detect and build recipes for that. Likewise if there's a single .prefPane or .plugin file enclosed in a zip.

Not essential for 1.0, though, since there are so few preference panes and internet plugins that don't already have recipes.

**Comment by sheagcraig** [comment]
I think add QuickLook plugins to the list as well. I just did one today.

**Comment by Jaharmi** [comment]
I believe that another issue with this is that some of these items can be code signed, but CodeSignatureVerifier doesn't (or didn't) handle bundles that end with extensions other than ".app".

**Comment by homebysix** [comment]
I may try to tackle this in the future, but a few example URLs would be useful for testing. If anybody has some specific preference panes and/or internet plugins in mind, please share!

**Comment by homebysix** [comment]
Found one example I'll use for testing:
https://bahoom.com/hyperdock/

**Comment by homebysix** [comment]
Made some progress on this in 867e125 in case anybody wants to clone the branch and test.

**Comment by homebysix** [comment]
Prefpanes, QLGenerators, and Internet Plug-Ins are now supported.
