### ISSUE TITLE
Goal of timing recipe generation

### ISSUE THREAD

**Issue by sheagcraig** [homebysix/recipe-robot#54]
What is the goal of timing the recipe generation?

Is it just for fun?

I think it's fun ;)

But if so, do we need to include timing for the argparsing, welcome message, etc?

**Comment by sheagcraig** [comment]
BTW-I've written a timing decorator and incorporated the results into the facts report.plist.

**Comment by homebysix** [comment]
Yes, I think it's just for fun. And I don't think we need to time every little thing the robot does. I just think it'd be fun to see how long it takes from when it starts processing an input path to the time it finishes generating recipes.

It used to take me something like 5-10 minutes per app to generate a recipe set, even when I used templates to start. Seeing that same recipe set take only 10-15 seconds makes me happy.

**Comment by sheagcraig** [comment]
Cool! I'll tighten things up and make sure it makes sense.
