### ISSUE TITLE
Cannot run against an app that already has a recipe available

### ISSUE THREAD

**Issue by 48kRAM** [homebysix/recipe-robot#61]
Thanks so much for this tool. I was excited to see what it would come up with for some apps that I've already written manual recipes for. Alas, this generates a fatal error.

It would be nice to compare my old recipes with what RR comes up with. Would it be possible to tell the nice robot to ignore an existing recipe and continue anyway?

Thanks

**Comment by homebysix** [comment]
Hi @48kRAM, I'll be publishing a video tutorial on how to do that soon. You'll need `--ignore-existing`, but there are a few other tips that will help you as well. Stay tuned.

**Comment by homebysix** [comment]
@48kRAM, you'll probably find this video useful for comparing your existing recipes to the recipes that Recipe Robot generates: https://www.youtube.com/watch?v=sItavxHraRQ&list=PLK1ZziC_XFWoDnSYU3__WRQCRpXA2fhXq&index=8
