### ISSUE TITLE
App is not displaying script output in realtime

### ISSUE THREAD

**Issue by homebysix** [homebysix/recipe-robot#71]
Upon dragging an app into the Recipe Robot app, there's a long delay, and then all the script output appears at once.

This happened earlier in development and somehow got fixed. I think it's broken again.

Here's a screencast of the behavior in action:

![not_real_time](https://cloud.githubusercontent.com/assets/7801391/11157714/e621ef1c-8a07-11e5-920f-dac8e7c9358f.gif)

**Comment by eahrold** [comment]
Fixed in https://github.com/homebysix/recipe-robot/commit/f99bc475755234ed079085fbf020aa693767b401
