### ISSUE TITLE
Provide feedback while downloading a file

### ISSUE THREAD

**Issue by jgstew** [homebysix/recipe-robot#72]
Recipe-robot seems stuck when it is downloading a file. It would be nice if there were some progress feedback during downloads.

### Related issues:
- https://github.com/homebysix/recipe-robot/issues/24
- https://github.com/homebysix/recipe-robot/issues/19

**Comment by homebysix** [comment]
#84 solves this for the script, but I'm not sure what the best solution for the app will be.

**Comment by homebysix** [comment]
https://github.com/homebysix/recipe-robot/commit/1ff91d3b6ec1b38cd2ab580d3f3af3c9f5c9ecbf should fix this for the app.
