### ISSUE TITLE
Need a command line switch to disable SSL certificate validation

### ISSUE THREAD

**Issue by jgstew** [homebysix/recipe-robot#76]
In some cases, it is useful to pull a download from an internal organization's webserver / software repo / etc... which may be using a self-signed cert. 

Also, if there is an odd issue with the certificate and after investigating, you find out that it has recently expired, it would be a bummer to have to wait around for the other end to fix the problem.

**Message:**
    [WARNING] Error encountered during file download. ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590))

**Screenshot:**
<img width="872" alt="screen shot 2015-11-16 at 9 09 08 pm" src="https://cloud.githubusercontent.com/assets/2439367/11203201/6b45b9a8-8ca6-11e5-9643-0f8011dffa23.png">
#### Related Issues:
- https://github.com/homebysix/recipe-robot/issues/19
- https://github.com/homebysix/recipe-robot/issues/74
- https://github.com/homebysix/recipe-robot/issues/72
- https://github.com/homebysix/recipe-robot/issues/24

**Comment by homebysix** [comment]
Recipe Robot 2+ now uses curl for downloading. I imagine both HTTP and HTTPS connections are supported, but HTTP connections with expired/incorrect certificates are not. (And shouldn't be, IMO.)
