### ISSUE TITLE
Add support for LANrev recipes, remove Absolute

### ISSUE THREAD

**Issue by patgmac** [homebysix/recipe-robot#94]
As you know, LANrevImporter has replaced AbsoluteManageExporter.

**Comment by homebysix** [comment]
@patgmac This is added to the https://github.com/homebysix/recipe-robot/tree/v1.0.2-beta branch, in case you want to try it.

Not sure when I'll release 1.0.2 but this will be included.

**Comment by patgmac** [comment]
Cool. Just wanted to make sure it was on your radar. I always forget to check branches. :-)

**Comment by patgmac** [comment]
Looks like you added LANrev as a type, but didn't remove Absolute. Is that correct?
Going forward, Absolute recipes should not be created. I don't think you need a transition period. Just a suggestion.

**Comment by homebysix** [comment]
Good suggestion! I'll make that change in 1.0.2 as well.
